server:
  compression:
    enabled: true
    mime-types: application/javascript
    min-response-size: 256
spring.resources:
  chain:
    strategy.content:
      enabled: true
      paths: /versioned/**